{{- if and (eq .Values.agentInjector.certificate.method "certmanager") .Values.agentInjector.enabled }}
apiVersion: cert-manager.io/v1
kind: {{ .Values.agentInjector.certificate.certmanager.issuerRef.kind }}
metadata:
  name: {{ .Values.agentInjector.certificate.certmanager.issuerRef.name }}
spec:
  selfSigned: {}
{{- end }}
