{{- if (eq .Values.trafficManager.serviceMesh.type "istio") }}
{{- if .Values.managerRbac.create }}
{{- if .Values.managerRbac.namespaced }}

{{- if not (has (include "traffic-manager.namespace" .) .Values.managerRbac.namespaces) }}
{{- fail (printf "Namespace %s must be included in managerRbac.namespaces (managerRbac.namespaces contains: %s)" (include "traffic-manager.namespace" .) (join "," .Values.managerRbac.namespaces)) }}
{{- end }}

{{- range .Values.managerRbac.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traffic-manager-istio
  namespace: {{ . }}
  labels:
    {{- include "telepresence.labels" $ | nindent 4 }}
rules:
- apiGroups:
  - "networking.istio.io"
  resources:
  - sidecars
  verbs:
  - create
  - list
  - get
  - watch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traffic-manager-istio
  namespace: {{ . }}
  labels:
    {{- include "telepresence.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traffic-manager-istio
subjects:
- kind: ServiceAccount
  name: traffic-manager
  namespace: {{ include "traffic-manager.namespace" $ }}
{{- end }}

{{- else }} {{- /* If not namespaced */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traffic-manager-istio-{{ include "traffic-manager.namespace" . }}
  labels:
    {{- include "telepresence.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "networking.istio.io"
  resources:
  - sidecars
  verbs:
  - create
  - list
  - get
  - watch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traffic-manager-istio-{{ include "traffic-manager.namespace" . }}
  labels:
    {{- include "telepresence.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traffic-manager-istio-{{ include "traffic-manager.namespace" . }}
subjects:
- kind: ServiceAccount
  name: traffic-manager
  namespace: {{ include "traffic-manager.namespace" . }}

{{- end }}
{{- end }}
{{- end }}
