{{- range $key, $value := .Values.containers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
spec:
  selector:
    app: {{ $key }}
  ports:
  - port: {{ $value.ports.port }}
    targetPort: {{ $value.ports.targetPort }}
  type: ClusterIP
{{- end }}